### ISSUE TITLE
Fail to compile, multiple definitions error

### ISSUE THREAD

**Issue by RikHOR1** [FIX94/Nintendont#777]
I can't seem to compile, getting multiple definition errors when compiling the kernel.
Is there something I'm missing or is there a code issue?

I'm sorry if this isn't the right place or if this is obviously a problem at my end, but I couldn't find a resolution so I figured it might have something to do with the code.

```
make -C kernel
make[1]: Map '/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel' wordt binnengegaan
AS      start.o
CC      common.o
CC      alloc.o
CC      GCAM.o
CC      JVSIO.o
CC      JVSIOMessage.o
CC      FST.o
CC      DI.o
CC      RealDI.o
CC      Patch.o
CC      PatchTimers.o
CC      TRI.o
CC      PatchWidescreen.o
CC      ISO.o
CC      Stream.o
CC      adp.o
CC      EXI.o
CC      SRAM.o
CC      GCNCard.o
CC      SI.o
CC      HID.o
CC      diskio.o
CC      Config.o
AS      utils_asm.o
CC      ES.o
CC      NAND.o
CC      main.o
AS      syscalls.o
CC      ReadSpeed.o
CC      vsprintf.o
CC      string.o
CC      prs.o
CC      SDI.o
CC      usb.o
CC      usbstorage.o
CC      wdvd.o
CC      sock.o
CC      lwbt/bte.o
CC      lwbt/btmemb.o
CC      lwbt/btmemr.o
CC      lwbt/btpbuf.o
CC      lwbt/hci.o
CC      lwbt/l2cap.o
CC      lwbt/physbusif.o
CC      BT.o
LD      kernel.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: alloc.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: alloc.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: GCAM.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: GCAM.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: JVSIO.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: JVSIO.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: JVSIOMessage.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: JVSIOMessage.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: FST.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: FST.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: DI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: DI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: RealDI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: RealDI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: Patch.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: Patch.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: PatchTimers.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: PatchTimers.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: TRI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: TRI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: PatchWidescreen.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: PatchWidescreen.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: ISO.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: ISO.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: Stream.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: Stream.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: EXI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: EXI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: SRAM.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: SRAM.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: GCNCard.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: GCNCard.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: SI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: SI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: HID.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: HID.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: diskio.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: diskio.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: Config.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: Config.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: ES.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: ES.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: NAND.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: NAND.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: main.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: main.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: ReadSpeed.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: ReadSpeed.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: vsprintf.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: vsprintf.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: string.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: string.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: prs.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: prs.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: SDI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: SDI.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: usb.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: usb.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: usbstorage.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: usbstorage.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: wdvd.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: wdvd.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: sock.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: sock.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/bte.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/bte.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/btmemb.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/btmemb.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/btmemr.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/btmemr.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/btpbuf.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/btpbuf.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/hci.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/hci.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/l2cap.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/l2cap.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/physbusif.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: lwbt/physbusif.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/./ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: BT.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: multiple definition of `TRIGames'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/global.h:199: first defined here
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: BT.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: multiple definition of `ipcmessage'; common.o:/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel/ipc.h:81: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:54: kernel.elf] Fout 1
make[1]: Map '/home/anonymous/Downloads/Nintendont-master/Nintendont/kernel' wordt verlaten
make: *** [Makefile:63: kernel] Fout 2

```

**Comment by 1ted59** [comment]
Fixed in #778 just need it to be merged into master.

**Comment by ccfman2004** [comment]
Using the 2 new files I can get a bit further but I still get a compile error.

`LD      kernel.elf
collect2.exe: error: ld returned 53 exit status
make[1]: *** [Makefile:54: kernel.elf] Error 1
make[1]: Leaving directory '/home/Chaz/devkitpro/nintendont/kernel'
make: *** [Makefile:63: kernel] Error 2
`

**Comment by geogolem** [comment]
that 53 exist status is a different issue, although I did still have a multiple definitions error even after  https://github.com/FIX94/Nintendont/pull/778

I added a comment to that PR, I copy it here for reference:

"Thanks for these changes, I needed to use them to build my branch while working on a fix. I noticed I needed to make a similar change to this file: loader/include/global.h as well. Its identical to the change in kernel/global.h"

regarding the exist code 53, i believe you are missing some library

**Comment by ccfman2004** [comment]
<img width="776" alt="Screen Shot 2020-08-25 at 5 09 54 PM" src="https://user-images.githubusercontent.com/79392/91228192-d5689b80-e6f5-11ea-8d09-46262e19151b.png">

**Comment by geogolem** [comment]
can you copy and paste your line 32 from the nintendont/kernel/Makefile?

**Comment by ccfman2004** [comment]
`LDFLAGS	:= -nostartfiles -nodefaultlibs -mbig-endian -Wl,-debug, --gc-sections,-T,kernel.ld,-Map,kernel.map -n`

**Comment by geogolem** [comment]
> `LDFLAGS := -nostartfiles -nodefaultlibs -mbig-endian -Wl,-debug, --gc-sections,-T,kernel.ld,-Map,kernel.map -n`

yes you need to removte the  space after debug, 

it should just be ,--gc-sections 

try that and let me know what you see

**Comment by ccfman2004** [comment]
<img width="975" alt="Screen Shot 2020-08-25 at 5 37 31 PM" src="https://user-images.githubusercontent.com/79392/91230533-b0762780-e6f9-11ea-94c1-b3390e789a09.png">

The zip directory is in the kernel folder and zip.exe is in that zip folder.

**Comment by geogolem** [comment]
ya, i ran into this issue too. the way i fixed it is: i changed line 22.

```ifeq ($(windows), 1)
	ZIP = zip/zip.exe
else
	ZIP = zip/zip.exe
endif```

i was on Windows but for some reason that $windows,1 thing is not working, changint the else to also point to zip/zip.exe fixed it for me.

you might have to do a make clean, make after changing that line in the makefile.

**Comment by ccfman2004** [comment]
EDIT: I reran the make command and wen pas the zip issue but now it says that "kernel_zip.h" no such file which is the same issue I got on Mac OS X 10.14.6

**Comment by geogolem** [comment]
i thnik the issue there, is that if the zip file failed, if you immediately run the make command, it doesnt bother creating the zip and fails in the next step. - i ran into a similar issue. I had to make the change I proposed above to ensure zip.exe is able to be properly executed, and then make clean

make

then onto the next error after the zip stuff - thats what happened for me. write back with more info and ill try to help till you get a successful build. It took me a whole night to get it to build properly - last night lol

**Comment by ccfman2004** [comment]
I got no build errors this time, plenty of warnings though.

**Comment by geogolem** [comment]
yes, i did have warnings.. and when i did eventually get my boot.dol, when i launch a game from usbloadergx, i just get a blackscreen. but if i launch the nintedont channel from HBC, it loads fine, i then loaded my game and tested my change --> it is successful .. I have no idea why the black screen from usbloader. My code change was small, so I assume the black screen and bloat of the dol (since it was about 0.5MB bigger than the one I was using without my changes, but my changes are very small) are attributed to new devkit etc. I dont really know thuogh. Those warnings are likely related.

**Comment by ccfman2004** [comment]
devkitPro is known to break stuff every now and again but that happens with a lot of toolchains

**Comment by geogolem** [comment]
> devkitPro is known to break stuff every now and again but that happens with a lot of toolchains

yes, and the codebase seems largely unchanged for a while. There are also a lot of pull requests..

**Comment by geogolem** [comment]
This is not totally related to this issue - butI mentioned a problem I was having with the latest build... Well I looked into it and managed to fix it. The issue is pretty well documented already here: https://github.com/FIX94/Nintendont/issues/712

**Comment by geogolem** [comment]
@carnage702 --> i think this one can be closed to...
